server:
  port: 9001

spring:
  application.name: oauth.service
  jpa:
    show-sql: true # for local testing
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc.batch_size: 45
        order_inserts: true
        order_updates: true
        jdbc.fetch_size: 1000
        jdbc.batch_versioned_data: true
  h2:
    console:
      enabled: true
      path: /h2-console
datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  driverClassName: org.h2.Driver
  initialization-mode : always

jwt.secret: secret

oauth:
  client:
    clientId: vms
    clientSecret: vmsSecret#$
    authorizedGrantTypes: password,refresh_token
    scopes: read,write
    accessTokenValiditySeconds: 60
    refreshTokenValiditySeconds: 7200

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: debug